version: '3'
services:
  jobe:
    image: trampgeek/jobeinabox:latest
    container_name: jobeinabox
    ports:
      - "4000:80"

  postgres:
    restart: always
    image: postgres:9.6.5
    command: postgres -p 5432

  django:
    build:
      context: .
      dockerfile: infrastructure/local-dev/Dockerfile
    volumes:
      - /csunplugged:/app
    environment:
      - PORT=8080
      - USE_DOCKER=yes
      - DATABASE_URL=postgres://postgres@postgres:5432/postgres
      - DJANGO_SETTINGS_MODULE=config.settings.local
      - INCLUDE_INCONTEXT_L10N=True
    depends_on:
      - postgres

  nginx:
    build:
      context: .
      dockerfile: ./infrastructure/nginx/Dockerfile
    volumes:
      - ./csunplugged/:/app/
      - /app/node_modules
    depends_on:
      - django
    ports:
      - "80:80"
