# Base docker-compose configuration for project.
# Local development uses docker-compose.yml and docker-compose.override.yml
# Production uses docker-compose.yml and docker-compose.prod.yml

version: "3.8"

services:
    django:
        build:
            context: .

    # File server
    nginx:
        image: nginx:1.19.10

    # Database
    postgres:
        build:
            context: .
            # Always use production image
            dockerfile: ./infrastructure/production/postgres/Dockerfile
        image: cs_unplugged_production_postgres
        healthcheck:
            test: ["CMD-SHELL", "pg_isready -U postgres"]
            start_period: 10s
            interval: 10s
            timeout: 5s
            retries: 3

    # jobe:
    #     image: trampgeek/jobeinabox:latest
