version: '3.8'

x-default-opts:
  &default-opts
  logging:
    options:
      max-size: '1m'
      max-file: '3'

services:
    postgres:
        <<: *default-opts
        image: postgres:13.3
        # TODO: Write test script that reads secret files
        # to get correct username
        # healthcheck:
        #     test: ["CMD-SHELL", "pg_isready -U postgres"]
        #     start_period: 10s
        #     interval: 10s
        #     timeout: 5s
        #     retries: 3
        deploy:
            replicas: 1
            placement:
            constraints:
                - node.role==worker
                - node.labels.role==data
            restart_policy:
                condition: on-failure
        environment:
            POSTGRES_DB_FILE: /run/secrets/cs-unplugged_postgres_db
            POSTGRES_USER_FILE: /run/secrets/cs-unplugged_postgres_user
            POSTGRES_PASSWORD_FILE: /run/secrets/cs-unplugged_postgres_password
        secrets:
            - cs-unplugged_postgres_db
            - cs-unplugged_postgres_user
            - cs-unplugged_postgres_password
        networks:
            - cs-unplugged_backend
        volumes:
            - postgres-data:/var/lib/postgresql/data:Z
            - postgres-data-backups:/backups:z

secrets:
    cs-unplugged_postgres_db:
        external: true
    cs-unplugged_postgres_user:
        external: true
    cs-unplugged_postgres_password:
        external: true

networks:
    cs-unplugged_backend:
        driver: overlay

volumes:
    postgres-data: {}
    postgres-data-backups: {}
    search-index: {}
