# Defines openings for incoming requests
entryPoints:
  web:
    address: ":80"
    # Global redirect from HTTP to HTTPS
    http:
      redirections:
        entryPoint:
          to: web-secure
          scheme: https
  web-secure:
    address: ":443"

tls:
  certificates:
    - certFile: "/etc/traefik/certs/local-cert.pem"
      keyFile: "/etc/traefik/certs/local-key.pem"

providers:
  docker:
    endpoint: "unix:///var/run/docker.sock"
    watch: true
    exposedByDefault: false
  file:
    directory: "/etc/traefik"
    watch: true

log:
  level: INFO
  format: common

global:
  sendAnonymousUsage: false

api:
  dashboard: true
  insecure: true
