name: Create and publish Docker images

on:
  workflow_dispatch:
  push:
    branches: ['develop', 'server-migration']

jobs:
  create-and-publish-dev-image:
    name: Create and publish dev image
    # if: github.ref == 'refs/heads/develop'
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        # ref: develop

      - name: Start system
        run: docker-compose -f docker-compose.local.yml up -d

      - name: Create production static files
        run: docker-compose -f docker-compose.local.yml run --rm --user="root" node npm run build

      - name: Migrate database
        run: docker-compose -f docker-compose.local.yml run --rm django python ./manage.py migrate

      - name: Load resources
        run: docker-compose -f docker-compose.local.yml run --rm django python ./manage.py loadresources

      - name: Make resource thumbnails
        run: docker-compose -f docker-compose.local.yml run --rm --user="root" django python ./manage.py makeresourcethumbnails

      - name: Make resources
        run: docker-compose -f docker-compose.local.yml run --rm --user="root" django python ./manage.py makeresources

      - name: Collect staticfiles
        run: docker-compose -f docker-compose.local.yml run --rm --user="root" django python manage.py collectstatic --no-input

      - name: Log in to the Container registry
        uses: docker/login-action@v1.10.0
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v2.6.1
        with:
          file: ./infrastructure/production/django/Dockerfile
          context: .
          push: true
          tags: ghcr.io/uccser/cs-unplugged:develop
          build-args: GIT_SHA=$GITHUB_SHA
