name: Test suite

on: [push]

jobs:
  test-content:
    name: Load content
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Start system
        run: ./dev start
      - name: Load content
        run: ./dev update

  test-general:
    name: General tests
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Start system
        run: ./dev start
      - name: Load content
        run: ./dev test_general
